GET http://localhost:3000/users/019ea0bb-c42b-7773-93c1-2d02e2a6a587
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxOWVhMGJiLWM0MmItNzc3My05M2MxLTJkMDJlMmE2YTU4NyIsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJqb2JzZWVrZXIiLCJpYXQiOjE3ODA4NzkwMjIsImV4cCI6MTc4MDg3OTkyMn0.onaMddKU3MtAr9TSuSKE5g1FtbSPCwWYTdKRqN9uu1U

### Register
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"    
}

### LOgin
POST http://localhost:3000/authentications
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### Refresh JWT
PUT http://localhost:3000/authentications
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxOWVhMGJiLWM0MmItNzc3My05M2MxLTJkMDJlMmE2YTU4NyIsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJqb2JzZWVrZXIiLCJpYXQiOjE3ODA4ODI3NTAsImV4cCI6MTc4MDk2OTE1MH0.MClwU0iUG603p-Ud5kRPwvCwJXb-UlLhAtNtq9ZnpoE"
}

### Logout
DELETE http://localhost:3000/authentications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxOWVhMGJiLWM0MmItNzc3My05M2MxLTJkMDJlMmE2YTU4NyIsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJqb2JzZWVrZXIiLCJpYXQiOjE3ODA4ODI3NjEsImV4cCI6MTc4MDg4MzY2MX0.oWlcpyhQlxPBj2_DNYxl9nXt0ZCDD8HRpP1NwuHw9ng
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxOWVhMGJiLWM0MmItNzc3My05M2MxLTJkMDJlMmE2YTU4NyIsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJqb2JzZWVrZXIiLCJpYXQiOjE3ODA4ODI3NTAsImV4cCI6MTc4MDk2OTE1MH0.MClwU0iUG603p-Ud5kRPwvCwJXb-UlLhAtNtq9ZnpoE"
}